authtest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
import django.views.static

urlpatterns = [
    url(r'^', include('u2f.urls', 'u2f')),
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
#    url(r'^admin/', admin.site.urls),
]

u2f/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^add_key/', views.add_key, name='add_key'),
    url(r'^twofactor/', views.twofactor, name='twofactor'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
]

u2f/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User

from django.conf import settings
from django.db import models

# Append to the users object
class U2FKey(models.Model):
    user = models.ForeignKey(User, related_name='u2f_keys')
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True)

    public_key = models.TextField()
    key_handle = models.TextField()
    app_id = models.TextField()

    def to_json(self):
        return {
            'publicKey': self.public_key,
            'keyHandle': self.key_handle,
            'appId': self.app_id,
        }

u2f/forms.py
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.

class LoginPromptForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)

class KeyResponseForm(forms.Form):
    response = forms.CharField()

u2f/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from u2f.forms import LoginPromptForm
from u2f.forms import KeyResponseForm

from django.contrib import auth
from u2flib_server import u2f_v2 as u2f

import json

# Create your views here.

def login(request):
    if request.method == 'POST':
        loginpromptform = LoginPromptForm(request.POST)
        if loginpromptform.is_valid():
            username = loginpromptform.cleaned_data['username']
            password = loginpromptform.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
#                auth.login(request, user)
                if user.u2f_keys.count() > 0:
                    print("There is a key registered")
                    request.session['authuser'] = user.pk;
                    request.session['backend'] = user.backend
                    return HttpResponseRedirect('/twofactor/')
                else:
                    print("Redirecting to Add_keyr")
                    print(user.backend)
                    auth.login(request, user)
                    return HttpResponseRedirect('/add_key/')

    loginpromptform = LoginPromptForm()
    context = {'loginprompt': loginpromptform}
    return render(request, 'u2f/login.html', context)

def add_key(request):

    if request.method == 'POST':
        # Add the key
        keyresponseform = KeyResponseForm(request.POST)
        if keyresponseform.is_valid():
            response = keyresponseform.cleaned_data['response']
            challenge = request.session['u2f_registration_challenge']
            print(challenge)
            del request.session['u2f_registration_challenge']
            device, attestation_cert = u2f.complete_register(challenge, response)
            request.user.u2f_keys.create(
                public_key=device['publicKey'],
                key_handle=device['keyHandle'],
                app_id=device['appId'],
            )
            print("%s\n\n\n%s" % (device, attestation_cert))
            return HttpResponseRedirect('/dashboard/')

    # Else if its a GET variable
    # Send them the request
    origin = '{scheme}://{host}'.format(
                scheme='https' if request.is_secure() else 'http',
                host=request.get_host(),
             )
    challenge = u2f.start_register(origin)
    request.session['u2f_registration_challenge'] = challenge
#    sign_requests = [u2f.start_authenticate(d.to_json()) for d in request.user.u2f_keys.all()]

    context = {'challenge': json.dumps(challenge)}
#               'sign_requests': sign_requests}

    return render(request, 'u2f/add_key.html', context)

def twofactor(request):
    print("All u2f keys")

    user = User.objects.get(pk=request.session['authuser'])
    print("The user is: %s" % user)
    challenges = [u2f.start_authenticate(u2f_key.to_json()) for u2f_key in user.u2f_keys.all()]

    if request.method == 'POST':
        u2f_response = KeyResponseForm(request.POST)

        if u2f_response.is_valid():
            device_response = u2f_response.cleaned_data['response']
            challenge = request.session['u2f_authentication_challenges'][0]

            device = user.u2f_keys.get() #key_handle=device_response['keyHandle'])
            print("Check this: %s" % device)

#            u2f_response_json = json.dumps(u2f_response.cleaned_data['response'])
            u2f_response_json = u2f_response.cleaned_data['response']

            login_counter, touch_asserted = u2f.verify_authenticate(device.to_json(), challenge, u2f_response_json,)
            print("Touch asserted: %s" % touch_asserted)
#            device.last_used_at = timezone.now()
#            device.save()
            del request.session['u2f_authentication_challenges']
            user.backend = request.session['backend']
            del request.session['backend']
            auth.login(request, user=user)
            return HttpResponseRedirect('/dashboard/')
    else:
        u2f_response = KeyResponseForm()
        print("The user is currently: %s" % user)
#        challenges = [user.u2f_keys.get().to_json()]
#        print(challenges)
        challenges = [u2f.start_authenticate(user.u2f_keys.get().to_json())]
        print(challenges)
        request.session['u2f_authentication_challenges'] = challenges
#        challenges = [u2f.start_authenticate(u2f_key.to_json()) for u2f_key in user.u2f_keys.all()]
        print("Final: %s" % str(json.dumps(challenges)))

        context = {'u2f_response': u2f_response,
                   'challenges': json.dumps(challenges)}
        return render(request, 'u2f/twofactor.html', context)

def dashboard(request):
    context = {}
    return render(request, 'u2f/dashboard.html', context)

u2f/templates/u2f/add_key.html
{% load staticfiles %}
{% load argonauts %}
{% load i18n %}
<script src="/static/u2f-api.js"></script>
Add-key stuff here

<script>
    function handleU2FError(resp) {
        if ( resp.errorCode ) {
            document.getElementById('u2f-status').textContent = 'Error with U2F';
            return true;
        } else {
            return false;
        }
    }
    if ( typeof window.u2f === 'undefined' )
      document.getElementById('u2f-not-defined-error').style.display = 'block';
</script>

<form method="post" id="u2f-form">
    {% csrf_token %}
    <input id="id_response" name="response" type="text" />
</form>

<script>
    var challenge = {{ challenge|safe }};
    var signRequests = {{ challenge|safe }};

    // Submit the form
    u2f.register([challenge], signRequests, function(resp) {
        var form = document.getElementById('u2f-form');
        form.response.value = JSON.stringify(resp);
        if ( ! handleU2FError(resp) ) {
            form.submit();
        }
    })
</script>

u2f/templates/u2f/dashboard.html
Nothing here

u2f/templates/u2f/login.html
<html>
    <form method=POST>
    {% csrf_token %}
    <table>
        {{ loginprompt }}
    </table>
    <button>Login</button>
    </form>
</html>

u2f/templates/u2f/twofactor.html
<script src="/static/u2f-api.js"></script>

Nothing here

<script>
    function handleU2FError(resp) {
        if ( resp.errorCode ) {
            document.getElementById('u2f-status').textContent = 'Error with U2F'
            return true;
        } else {
            return false;
        }
    }
    if ( typeof window.u2f === 'undefined' )
        document.getElementById('u2f-not-defined-error').style.display = 'block';
</script>


<form method="post" id="u2f-form">
    {% csrf_token %}
    {{ u2f_response }}
</form>
Update 1
<script>                                                                     
    var challenges = {{ challenges|safe }};
    u2f.sign(challenges, function(resp) { 
        var form = document.getElementById('u2f-form');
        form.response.value = JSON.stringify(resp);
        if ( ! handleU2FError(resp) ) {
            form.submit();
        }
    })
</script>